name: CI
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Install Rust ${{ matrix.rust }}
        run: |
          rustup self update
          rustup update ${{ matrix.rust }}
          rustup default ${{ matrix.rust }}
          rustc -vV
      - name: Run tests
        run: cargo test

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Install Rust Stable
        run: |
          rustup update stable
          rustup default stable
          rustup component add rustfmt
      - name: Run rustfmt
        run: cargo fmt -- --check
